### ISSUE TITLE
PortScanner() launch the scan() with an automatic "-oX -" arguments 

### ISSUE THREAD

**Issue by dplastico** [MyKings/python-masscan#12]
Hello,

When executing a scan() the arguments "-oX" and a "-" are hardcoded and passed to the scan with also  the "argumets=" I would think is better to not have this hardcoded since I do not want to have all my scans being exported also the "-" generates issues when passing custom arguments

I fixed this deleting the arguments in line 269 of masscan.py
Before:
![image](https://user-images.githubusercontent.com/42063594/55747765-0108ba00-5a0b-11e9-88a7-4d27924a12c7.png)
After:
![image](https://user-images.githubusercontent.com/42063594/55747869-475e1900-5a0b-11e9-8647-c6f02b5d01e4.png)

I don't know how to report this things (1st time in github) so sorry if this was no the proper way to report it

Edit: typo
Renato.

**Comment by MyKings** [comment]
Hi, @dplastico 

```python
args = [self._masscan_path, '-oX', '-']  ...
```

* The `-oX` here means to save the masscan scan results in xml file format.
* `-` means that the stdout result of `masscan -oX` is taken as stdin , so that no file is generated and the scan result is taken, so it cannot be deleted here.

Finally, thank you for your support of python-masscan.
