### ISSUE TITLE
Broken Output

### ISSUE THREAD

**Issue by Besix2** [MyKings/python-masscan#49]
When I use the example script it only returns the cli command.

`{"command_line": "masscan -oJ - 172.0.8.78/24 -p 22,80,8080 --max-rate 1000", "scan": {}}`

Its not even starting scanning. It just skips the scanning process.

**Comment by Blotz** [comment]
It appears you are running the example code off the README.md

This appears to be running correctly.
The issue is that 127.x.x.x is a reserved ip range and unless you have set up something to run on it, there wont be any ip addresses on that network.

In otherwords, because 127.x.x.x is a reserved ip range, there will not be any available ip addresses to scan. This is why the `"scan": {}` section is empty.

Try changing the target ip range to something more likely to run something such as `192.168.0.1/24` or `192.168.0.1/24` or `1.1.1.1`. hope this helps!

**Comment by Besix2** [comment]
I already tried it with 0.0.0.0-255.255.255.255 and the normal mass an returned values but the not the script.

**Comment by Besix2** [comment]
Turns out I need sudo else masscan wont return anything.
